apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux-demo-ccloud-operator
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: ccloud-operator
  template:
    metadata:
      labels:
        app: ccloud-operator
    spec:
      containers:
      - name: ccloud-operator
        image: cnfldemos/ccloud-operator:sha-cca98ee
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: cc.ccloud-secrets
        resources:
          limits:  
            cpu: 2000m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 64Mi
      serviceAccountName: ccloud-admin-sa
